version: '3.8'

services:
  db:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123434
      POSTGRES_DB: tb
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-go-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
